// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (c) 2020-2026 Michal Dengusiak & Jakub Ziolkowski and contributors

using SAM.Core;
using SAM.Core.OCCT;
using SAM.Geometry.Planar;
using SAM.Geometry.Spatial;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SAM.Geometry.OCCT
{
    public static partial class Create
    {
        /// <summary>
        /// Creates closed Shells from vertical wall Face3Ds only (issue #24): the
        /// floors and roofs are generated by the OCCT engine. Wall bottom/top
        /// elevations are clustered within <paramref name="snapTolerance"/> (so walls
        /// that do not meet at exactly the same level still share one floor level),
        /// a padded horizontal rectangular patch is added per elevation, and a single
        /// BOPAlgo_MakerVolume pass over walls + patches produces the cells. Regions
        /// not enclosed laterally by walls stay unbounded and are dropped by OCCT;
        /// plan-enclosed voids (courtyards) become shells, matching the managed SAM
        /// CreateShells behaviour. Walls of different heights produce stacked cells
        /// per level - merge them downstream with MergeSmallShells/ShellsUnion.
        /// <para>
        /// With <paramref name="roofMode"/> = <see cref="OcctRoofMode.Sloped"/> the
        /// top is capped by a single roof that follows the wall tops instead of a flat
        /// level: when the wall tops are coplanar (flat, mono-pitch, any single tilt)
        /// the roof is one planar face; when they are not (gable, hip, stepped tops)
        /// the wall-top envelope is Delaunay-triangulated. Floors stay horizontal at
        /// the clustered wall bottom elevations.
        /// </para>
        /// <paramref name="horizontalFace3Ds"/> returns the newly created floor/roof
        /// faces (horizontal floors plus the generated roof), deduplicated by OCCT
        /// topology key so an interior floor shared by two cells appears once.
        /// <para>
        /// When <paramref name="point3Ds"/> are supplied, only shells that contain a
        /// point are kept (point-in-solid is classified by the OCCT kernel, with a
        /// managed ray-cast fallback) - drop one marker per room to discard courtyards
        /// and other plan-enclosed voids. When the walls do not enclose a volume the
        /// open boundary is reported (SAM_OCCT_OPEN_SHELL_ANALYSIS) so the gap is
        /// actionable instead of an empty result.
        /// </para>
        /// Non-planar input is not supported by the native make_face - triangulate
        /// such faces first (SAMOCCT.TriangulateSurface). Returns null on failure -
        /// inspect result diagnostics (SAM_OCCT_VERTICAL_SHELLS_*).
        /// </summary>
        public static List<Shell> ShellsFromVerticalFace3Ds(
            IEnumerable<Face3D> face3Ds,
            out List<Face3D> horizontalFace3Ds,
            out OcctCellComplexResult result,
            IEnumerable<double> elevations = null,
            double snapTolerance = Tolerance.MacroDistance,
            OcctBuildOptions options = null,
            double angleTolerance = Tolerance.Angle,
            double distanceTolerance = Tolerance.MacroDistance,
            OcctRoofMode roofMode = OcctRoofMode.Flat,
            IEnumerable<Point3D> point3Ds = null)
        {
            horizontalFace3Ds = null;
            result = new OcctCellComplexResult();

            List<Face3D> face3Ds_All = face3Ds?.Where(x => x != null).ToList();
            if (face3Ds_All == null || face3Ds_All.Count == 0)
            {
                result.AddDiagnostic(OcctDiagnosticSeverity.Error, "SAM_OCCT_VERTICAL_SHELLS_INPUT_EMPTY", "No Face3D geometry was supplied.");
                return null;
            }

            // Partition the input (mixed input): vertical faces are walls; non-vertical
            // faces are user-supplied floor/roof caps - they bound the cells like walls,
            // but in addition suppress auto-generation at the levels they already cover,
            // so only the missing caps are generated. Every plane is remembered so a
            // result face lying on an input face is not reported as newly created.
            double maxNormalZ = Math.Sin(angleTolerance);
            // A face is a cap (floor/roof) when it is substantially horizontal and a wall
            // otherwise. The split must use a generous angle, NOT the near-zero angle
            // tolerance: a battered or drooped wall (tilted a few degrees) is still a wall,
            // and misreading it as a cap would wrongly suppress the floor/roof under it.
            // |normal.Z| > 0.5 keeps walls within ~30 deg of vertical as walls and treats
            // roofs up to ~60 deg of pitch as caps.
            const double capNormalZ = 0.5;
            List<Plane> planes_All = new List<Plane>();
            List<Face3D> walls = new List<Face3D>();
            List<Face3D> caps = new List<Face3D>();
            for (int i = 0; i < face3Ds_All.Count; i++)
            {
                Plane plane = face3Ds_All[i].GetPlane();
                if (plane == null)
                {
                    result.AddDiagnostic(OcctDiagnosticSeverity.Warning, "SAM_OCCT_VERTICAL_SHELLS_NON_VERTICAL_FACE", "Face3D plane could not be computed.", i);
                    continue;
                }

                planes_All.Add(plane);
                if (Math.Abs(plane.Normal.Z) > capNormalZ)
                {
                    caps.Add(face3Ds_All[i]);
                }
                else
                {
                    walls.Add(face3Ds_All[i]);
                }
            }

            if (caps.Count != 0)
            {
                result.AddDiagnostic(OcctDiagnosticSeverity.Info, "SAM_OCCT_VERTICAL_SHELLS_USER_CAP", string.Format("{0} supplied floor/roof cap face(s) detected; auto-generating only the missing caps.", caps.Count));
            }

            BoundingBox3D boundingBox3D = new BoundingBox3D(face3Ds_All.ConvertAll(x => x.GetBoundingBox()));
            if (boundingBox3D == null || !boundingBox3D.IsValid())
            {
                result.AddDiagnostic(OcctDiagnosticSeverity.Error, "SAM_OCCT_VERTICAL_SHELLS_INPUT_EMPTY", "Bounding box of the input Face3Ds could not be computed.");
                return null;
            }

            options = options == null ? new OcctBuildOptions() : new OcctBuildOptions(options);

            // Patch must overhang the walls so MakerVolume cuts cleanly through them.
            double margin = Math.Max(1.0, boundingBox3D.Min.Distance(boundingBox3D.Max) * 0.1);

            List<Face3D> allFace3Ds = new List<Face3D>(face3Ds_All);

            if (roofMode == OcctRoofMode.Sloped)
            {
                // Floors: flat patches at the clustered wall bottom elevations (or the
                // supplied override), minus any a user cap already covers. The top is
                // left to the wall-top roof below.
                List<double> floorElevations = elevations != null
                    ? Query.ClusteredElevations(elevations, snapTolerance)
                    : Query.ClusteredElevations(walls.ConvertAll(x => x.GetBoundingBox().Min.Z), snapTolerance);
                if (floorElevations == null || floorElevations.Count == 0)
                {
                    result.AddDiagnostic(OcctDiagnosticSeverity.Error, "SAM_OCCT_VERTICAL_SHELLS_INSUFFICIENT_ELEVATIONS", "At least one floor elevation is required to cap the walls.");
                    return null;
                }

                List<double> floorElevations_Generated = UncappedElevations(floorElevations, caps, snapTolerance);
                int floorElevations_Suppressed = floorElevations.Count - floorElevations_Generated.Count;
                string floorElevations_Note = floorElevations_Suppressed > 0 ? string.Format(" {0} detected level(s) already covered by supplied caps were skipped.", floorElevations_Suppressed) : string.Empty;
                result.AddDiagnostic(OcctDiagnosticSeverity.Info, "SAM_OCCT_VERTICAL_SHELLS_ELEVATIONS", floorElevations_Generated.Count == 0
                    ? string.Format("All floor levels are already covered by supplied caps; generating only a sloped roof from the wall tops.{0}", floorElevations_Note)
                    : string.Format("Generating floor level(s) at {0} and a sloped roof from the wall tops.{1}", string.Join(", ", floorElevations_Generated.Select(x => x.ToString("0.###"))), floorElevations_Note));

                allFace3Ds.AddRange(HorizontalPatches(floorElevations_Generated, boundingBox3D, margin));

                // Auto-roof from the wall tops, unless a user cap already covers them.
                double wallTopElevation = walls.Count == 0 ? boundingBox3D.Max.Z : walls.Max(x => x.GetBoundingBox().Max.Z);
                if (CapCovers(caps, wallTopElevation, snapTolerance))
                {
                    result.AddDiagnostic(OcctDiagnosticSeverity.Info, "SAM_OCCT_VERTICAL_SHELLS_ROOF_SUPPLIED", "A supplied cap already covers the wall tops; using it as the roof instead of generating one.");
                }
                else
                {
                    List<Face3D> roofFace3Ds = RoofFace3Ds(walls, boundingBox3D, margin, snapTolerance, distanceTolerance, maxNormalZ, options.Tolerance, out string roofKind, out int roofCount);
                    if (roofFace3Ds == null || roofFace3Ds.Count == 0)
                    {
                        result.AddDiagnostic(OcctDiagnosticSeverity.Error, "SAM_OCCT_VERTICAL_SHELLS_ROOF_FAILED", "Could not derive a roof surface from the wall tops (need at least three non-collinear top points).");
                        return null;
                    }

                    result.AddDiagnostic(OcctDiagnosticSeverity.Info, roofKind == "planar" ? "SAM_OCCT_VERTICAL_SHELLS_ROOF_PLANAR" : "SAM_OCCT_VERTICAL_SHELLS_ROOF_TRIANGULATED", roofKind == "planar" ? "Wall tops are coplanar; roof created as a single planar (pitched) face." : string.Format("Wall tops are not coplanar; roof triangulated into {0} face(s) from the wall-top envelope.", roofCount));

                    allFace3Ds.AddRange(roofFace3Ds);
                }
            }
            else
            {
                // Flat: a horizontal patch at every clustered bottom/top elevation a user
                // cap does not already cover.
                List<double> elevations_Temp = elevations != null ? Query.ClusteredElevations(elevations, snapTolerance) : Query.ClusteredElevations(walls, snapTolerance);
                if (elevations_Temp == null || elevations_Temp.Count < 2)
                {
                    result.AddDiagnostic(OcctDiagnosticSeverity.Error, "SAM_OCCT_VERTICAL_SHELLS_INSUFFICIENT_ELEVATIONS", "At least two distinct elevations are required to cap the walls with floors and roofs.");
                    return null;
                }

                List<double> elevations_Generated = UncappedElevations(elevations_Temp, caps, snapTolerance);
                int elevations_Suppressed = elevations_Temp.Count - elevations_Generated.Count;
                string elevations_Note = elevations_Suppressed > 0 ? string.Format(" {0} detected level(s) already covered by supplied caps were skipped.", elevations_Suppressed) : string.Empty;
                result.AddDiagnostic(OcctDiagnosticSeverity.Info, "SAM_OCCT_VERTICAL_SHELLS_ELEVATIONS", string.Format("Generating horizontal patches at {0} elevation(s){1}.{2}", elevations_Generated.Count, elevations_Generated.Count == 0 ? string.Empty : ": " + string.Join(", ", elevations_Generated.Select(x => x.ToString("0.###"))), elevations_Note));

                allFace3Ds.AddRange(HorizontalPatches(elevations_Generated, boundingBox3D, margin));
            }

            bool built = Native.OcctCellComplexBuilder.TryBuild(allFace3Ds, options, result);
            if (!built || result.Cells == null || result.Cells.Count == 0)
            {
                // No enclosed volume. When the kernel ran (so this is a real geometry
                // gap, not a missing native library), report where the boundary is open
                // - naked edges, the gap bounding box and the longest gap location - so
                // the user can fix the drawing. TryBuild already runs this on a hard
                // failure; add it for the "built but zero cells" case too.
                if (result.NativeAvailable)
                {
                    if (!result.Diagnostics.Any(x => x.Code == "SAM_OCCT_OPEN_SHELL_ANALYSIS"))
                    {
                        Native.OcctOpenShellAnalysis.Report(walls, options, result);
                    }

                    result.AddDiagnostic(OcctDiagnosticSeverity.Warning, "SAM_OCCT_VERTICAL_SHELLS_OPEN", "The walls do not enclose a volume, so no shells were created. See SAM_OCCT_OPEN_SHELL_ANALYSIS for the open-boundary location (note: wall tops and bottoms are expected to be open).");
                }

                return null;
            }

            // Point selection: keep only the shells that contain a supplied point (one
            // marker per room), discarding courtyards and other plan-enclosed voids.
            List<OcctCell> cells = SelectCells(result.Cells, point3Ds, options, distanceTolerance, result);
            if (cells.Count == 0)
            {
                // The build succeeded but the points matched nothing; return an empty
                // (not null) result - the diagnostics explain why.
                horizontalFace3Ds = new List<Face3D>();
                return new List<Shell>();
            }

            // The generated floor/roof faces are the cell faces that did not come from
            // an input wall. Walls are vertical (the planar floors/roofs never coincide
            // with them) and any kept non-vertical input is excluded the same way, so a
            // sloped roof that aligns with a tilted wall is not double-reported. Interior
            // floors shared by two cells are deduped by the OCCT topology key.
            horizontalFace3Ds = new List<Face3D>();
            HashSet<int> topologyKeys = new HashSet<int>();
            double minDotProduct = Math.Cos(angleTolerance);
            // MakerVolume welds vertices up to fuzzyTolerance, so a cell face that came
            // from an input wall/cap can end up that far off the original plane. Match
            // against the larger of the two tolerances, otherwise a high fuzzyTolerance
            // makes welded walls look "newly generated" and pollutes horizontalFace3Ds.
            double inputPlaneTolerance = Math.Max(distanceTolerance, options.FuzzyTolerance);
            foreach (OcctCell cell in cells)
            {
                if (cell?.Faces == null)
                {
                    continue;
                }

                foreach (OcctCellFace cellFace in cell.Faces)
                {
                    Face3D face3D = cellFace?.Face3D;
                    Plane facePlane = face3D?.GetPlane();
                    if (facePlane == null)
                    {
                        continue;
                    }

                    // Flat mode keeps only horizontal faces (a cheap guard against
                    // stray native slivers); sloped mode keeps tilted roofs too.
                    if (roofMode != OcctRoofMode.Sloped && Math.Abs(facePlane.Normal.Z) < minDotProduct)
                    {
                        continue;
                    }

                    if (CoplanarWithAny(facePlane, planes_All, minDotProduct, inputPlaneTolerance))
                    {
                        continue;
                    }

                    if (cellFace.TopologyKey != 0 && !topologyKeys.Add(cellFace.TopologyKey))
                    {
                        continue;
                    }

                    horizontalFace3Ds.Add(face3D);
                }
            }

            result.AddDiagnostic(OcctDiagnosticSeverity.Info, "SAM_OCCT_VERTICAL_SHELLS_BUILD_SUCCESS", string.Format("OCCT created {0} shell(s) and {1} generated floor/roof face(s) from {2} wall(s) and {3} supplied cap(s).", cells.Count, horizontalFace3Ds.Count, walls.Count, caps.Count));
            return cells.ConvertAll(x => x.Shell).FindAll(x => x != null);
        }

        /// <summary>
        /// The subset of <paramref name="elevations"/> not already covered by a supplied
        /// cap. An elevation is covered when it falls within a cap's Z extent (the cap's
        /// bounding box, padded by <paramref name="snapTolerance"/>) - so a horizontal
        /// cap suppresses its own level and a sloped cap suppresses the band it spans.
        /// </summary>
        private static List<double> UncappedElevations(List<double> elevations, List<Face3D> caps, double snapTolerance)
        {
            if (caps == null || caps.Count == 0)
            {
                return elevations;
            }

            List<double> result = new List<double>();
            foreach (double elevation in elevations)
            {
                if (!CapCovers(caps, elevation, snapTolerance))
                {
                    result.Add(elevation);
                }
            }

            return result;
        }

        /// <summary>True when a supplied cap's Z extent (padded by <paramref name="snapTolerance"/>) contains <paramref name="elevation"/>.</summary>
        private static bool CapCovers(List<Face3D> caps, double elevation, double snapTolerance)
        {
            if (caps == null)
            {
                return false;
            }

            foreach (Face3D cap in caps)
            {
                BoundingBox3D boundingBox3D = cap?.GetBoundingBox();
                if (boundingBox3D == null)
                {
                    continue;
                }

                if (elevation >= boundingBox3D.Min.Z - snapTolerance && elevation <= boundingBox3D.Max.Z + snapTolerance)
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>Padded horizontal rectangular patches (one per elevation) covering the footprint.</summary>
        private static List<Face3D> HorizontalPatches(IEnumerable<double> elevations, BoundingBox3D boundingBox3D, double margin)
        {
            List<Face3D> result = new List<Face3D>();
            List<Point3D> cornerPoint3Ds = boundingBox3D.GetPoints();
            foreach (double elevation in elevations)
            {
                Plane plane = new Plane(new Point3D(0, 0, elevation), new Vector3D(0, 0, 1));

                List<Point2D> point2Ds = cornerPoint3Ds?.ConvertAll(x => plane.Convert(x)).FindAll(x => x != null);
                if (point2Ds == null || point2Ds.Count == 0)
                {
                    continue;
                }

                Face3D patchFace3D = new Face3D(plane, new Rectangle2D(new BoundingBox2D(point2Ds, margin)));
                if (patchFace3D != null)
                {
                    result.Add(patchFace3D);
                }
            }

            return result;
        }

        /// <summary>
        /// Roof faces following the wall tops. The upper envelope of the wall boundary
        /// vertices (the highest Z per plan location) is the roof. If those points are
        /// coplanar the roof is a single padded planar patch on the fitted plane (flat
        /// or any single tilt); otherwise the envelope is Delaunay-triangulated in plan
        /// and each triangle lifted back to its true vertex heights (gable/hip/stepped).
        /// MakerVolume trims either form to each room, like the flat patch.
        /// </summary>
        private static List<Face3D> RoofFace3Ds(List<Face3D> face3Ds_Wall, BoundingBox3D boundingBox3D, double margin, double snapTolerance, double distanceTolerance, double maxNormalZ, double tolerance, out string roofKind, out int roofCount)
        {
            roofKind = null;
            roofCount = 0;

            List<Point3D> envelope = WallTopEnvelope(face3Ds_Wall, snapTolerance);
            if (envelope == null || envelope.Count < 3)
            {
                return null;
            }

            // Coplanar wall tops (flat, mono-pitch, any single tilt): the roof is one
            // planar face built straight from the fitted plane and handed to OCCT - no
            // managed meshing. The plane is fit from three spread, non-collinear top
            // points, so it is independent of the (arbitrary) envelope order.
            Plane plane = RoofPlane(envelope, tolerance);
            if (plane != null && Math.Abs(plane.Normal.Z) > maxNormalZ && envelope.TrueForAll(x => Math.Abs(plane.Distance(x)) <= distanceTolerance))
            {
                List<Point2D> point2Ds = boundingBox3D.GetPoints().ConvertAll(x => plane.Convert(x)).FindAll(x => x != null);
                if (point2Ds != null && point2Ds.Count != 0)
                {
                    Face3D patch = new Face3D(plane, new Rectangle2D(new BoundingBox2D(point2Ds, margin)));
                    if (patch != null)
                    {
                        roofKind = "planar";
                        roofCount = 1;
                        return new List<Face3D> { patch };
                    }
                }
            }

            // Non-coplanar tops (gable, hip, stepped) over a possibly multi-room plan:
            // OCCT has no point-set/terrain triangulation - its native triangulator meshes
            // a single boundary loop, which would bulge a roof and cannot span several
            // rooms - so the wall-top envelope is Delaunay-triangulated in plan and lifted
            // to the true heights. These flat triangles are only candidate faces; the
            // shells themselves are still built by the OCCT MakerVolume pass.
            Plane planeXY = new Plane(new Point3D(0, 0, 0), new Vector3D(0, 0, 1));
            List<Point2D> sites = envelope.ConvertAll(x => planeXY.Convert(x));
            List<Triangle2D> triangle2Ds = SAM.Geometry.Planar.Query.Triangulate(sites, tolerance);
            if (triangle2Ds == null || triangle2Ds.Count == 0)
            {
                return null;
            }

            List<Face3D> result = new List<Face3D>();
            foreach (Triangle2D triangle2D in triangle2Ds)
            {
                List<Point2D> point2Ds = triangle2D?.GetPoints();
                if (point2Ds == null || point2Ds.Count != 3)
                {
                    continue;
                }

                // Delaunay sites are the projected envelope points, so each triangle
                // vertex maps back to a real (true-height) envelope point.
                Triangle3D triangle3D = new Triangle3D(
                    envelope[NearestSite(sites, point2Ds[0])],
                    envelope[NearestSite(sites, point2Ds[1])],
                    envelope[NearestSite(sites, point2Ds[2])]);

                Face3D face3D = new Face3D(triangle3D);
                if (face3D != null)
                {
                    result.Add(face3D);
                }
            }

            if (result.Count == 0)
            {
                return null;
            }

            roofKind = "triangulated";
            roofCount = result.Count;
            return result;
        }

        /// <summary>Upper envelope of the wall boundary vertices: the highest Z at each plan location (clustered in XY by <paramref name="snapTolerance"/>).</summary>
        private static List<Point3D> WallTopEnvelope(List<Face3D> face3Ds_Wall, double snapTolerance)
        {
            List<Point3D> envelope = new List<Point3D>();
            foreach (Face3D face3D in face3Ds_Wall)
            {
                List<Point3D> point3Ds = (face3D?.GetExternalEdge3D() as ISegmentable3D)?.GetPoints();
                if (point3Ds == null)
                {
                    continue;
                }

                foreach (Point3D point3D in point3Ds)
                {
                    if (point3D == null)
                    {
                        continue;
                    }

                    bool merged = false;
                    for (int i = 0; i < envelope.Count; i++)
                    {
                        double dx = envelope[i].X - point3D.X;
                        double dy = envelope[i].Y - point3D.Y;
                        if (Math.Sqrt((dx * dx) + (dy * dy)) > snapTolerance)
                        {
                            continue;
                        }

                        if (point3D.Z > envelope[i].Z)
                        {
                            envelope[i] = new Point3D(envelope[i].X, envelope[i].Y, point3D.Z);
                        }

                        merged = true;
                        break;
                    }

                    if (!merged)
                    {
                        envelope.Add(point3D);
                    }
                }
            }

            return envelope;
        }

        /// <summary>
        /// Plane fit through the wall-top envelope from three spread, non-collinear
        /// points (the farthest pair, then the point farthest from their line). Being
        /// built from a real triangle it is order-independent, unlike a polygon normal
        /// over arbitrarily ordered points. Returns null for coincident/collinear input.
        /// </summary>
        private static Plane RoofPlane(List<Point3D> point3Ds, double tolerance)
        {
            Point3D point3D_A = point3Ds[0];

            Point3D point3D_B = null;
            double maxDistance = tolerance;
            foreach (Point3D point3D in point3Ds)
            {
                double distance = point3D_A.Distance(point3D);
                if (distance > maxDistance)
                {
                    maxDistance = distance;
                    point3D_B = point3D;
                }
            }

            if (point3D_B == null)
            {
                return null;
            }

            Vector3D vector3D_AB = new Vector3D(point3D_A, point3D_B);
            Vector3D normal = null;
            double maxLength = tolerance;
            foreach (Point3D point3D in point3Ds)
            {
                Vector3D cross = vector3D_AB.CrossProduct(new Vector3D(point3D_A, point3D));
                if (cross.Length > maxLength)
                {
                    maxLength = cross.Length;
                    normal = cross;
                }
            }

            if (normal == null)
            {
                return null;
            }

            return new Plane(point3D_A, normal.Unit);
        }

        /// <summary>Index of the site nearest to <paramref name="point2D"/> (the source envelope point of a Delaunay vertex).</summary>
        private static int NearestSite(List<Point2D> sites, Point2D point2D)
        {
            int index = 0;
            double distanceSquared = double.MaxValue;
            for (int i = 0; i < sites.Count; i++)
            {
                double dx = sites[i].X - point2D.X;
                double dy = sites[i].Y - point2D.Y;
                double d = (dx * dx) + (dy * dy);
                if (d < distanceSquared)
                {
                    distanceSquared = d;
                    index = i;
                }
            }

            return index;
        }

        /// <summary>True when <paramref name="plane"/> is parallel to and coincident with any plane in <paramref name="planes"/>.</summary>
        private static bool CoplanarWithAny(Plane plane, List<Plane> planes, double minDotProduct, double distanceTolerance)
        {
            foreach (Plane plane_Other in planes)
            {
                if (plane_Other == null)
                {
                    continue;
                }

                if (Math.Abs(plane.Normal.DotProduct(plane_Other.Normal)) < minDotProduct)
                {
                    continue;
                }

                if (plane_Other.Distance(plane.Origin) > distanceTolerance)
                {
                    continue;
                }

                return true;
            }

            return false;
        }

        /// <summary>
        /// Keeps the cells whose shell contains at least one of <paramref name="point3Ds"/>
        /// (one marker per room), discarding courtyards and other plan-enclosed voids.
        /// Returns every cell unchanged when no points are supplied. Records selection,
        /// duplicate (more than one point in a shell) and unmatched-point diagnostics.
        /// </summary>
        private static List<OcctCell> SelectCells(IReadOnlyList<OcctCell> cells, IEnumerable<Point3D> point3Ds, OcctBuildOptions options, double tolerance, OcctCellComplexResult result)
        {
            List<OcctCell> cells_All = new List<OcctCell>();
            foreach (OcctCell cell in cells)
            {
                if (cell != null)
                {
                    cells_All.Add(cell);
                }
            }

            List<Point3D> point3Ds_Temp = point3Ds?.Where(x => x != null).ToList();
            if (point3Ds_Temp == null || point3Ds_Temp.Count == 0)
            {
                return cells_All;
            }

            List<OcctCell> cells_Kept = new List<OcctCell>();
            int[] matchCount = new int[point3Ds_Temp.Count];
            bool duplicate = false;
            foreach (OcctCell cell in cells_All)
            {
                List<int> insideIndices = PointsInsideShell(cell.Shell, point3Ds_Temp, options, tolerance);
                if (insideIndices.Count == 0)
                {
                    continue;
                }

                cells_Kept.Add(cell);
                if (insideIndices.Count > 1)
                {
                    duplicate = true;
                }

                foreach (int index in insideIndices)
                {
                    matchCount[index]++;
                }
            }

            int unmatched = matchCount.Count(x => x == 0);

            result.AddDiagnostic(OcctDiagnosticSeverity.Info, "SAM_OCCT_VERTICAL_SHELLS_POINT_SELECTION", string.Format("Point selection kept {0} of {1} shell(s) using {2} point(s).", cells_Kept.Count, cells_All.Count, point3Ds_Temp.Count));
            if (duplicate)
            {
                result.AddDiagnostic(OcctDiagnosticSeverity.Warning, "SAM_OCCT_VERTICAL_SHELLS_POINT_DUPLICATE", "One or more shells contain more than one selection point.");
            }

            if (unmatched > 0)
            {
                result.AddDiagnostic(OcctDiagnosticSeverity.Warning, "SAM_OCCT_VERTICAL_SHELLS_POINT_UNMATCHED", string.Format("{0} selection point(s) were not inside any shell.", unmatched));
            }

            if (cells_Kept.Count == 0)
            {
                result.AddDiagnostic(OcctDiagnosticSeverity.Warning, "SAM_OCCT_VERTICAL_SHELLS_POINT_NONE", "No shells contained any of the supplied selection points.");
            }

            return cells_Kept;
        }

        /// <summary>
        /// Indices of the points inside <paramref name="shell"/>. Classification runs on
        /// the OCCT kernel: the shell's own faces are rebuilt once into a retained native
        /// topology and each point is tested with the solid classifier. Falls back to the
        /// managed ray-cast (same test as SAMAnalytical.CreateShells) when the native
        /// library is unavailable or a point cannot be classified.
        /// </summary>
        private static List<int> PointsInsideShell(Shell shell, List<Point3D> point3Ds, OcctBuildOptions options, double tolerance)
        {
            List<int> indices = new List<int>();
            if (shell == null)
            {
                return indices;
            }

            List<Face3D> face3Ds = shell.Face3Ds?.FindAll(x => x != null);
            OcctCellComplexResult result_Shell = null;
            OcctTopology topology = null;
            if (face3Ds != null && face3Ds.Count != 0)
            {
                OcctBuildOptions options_Retain = new OcctBuildOptions(options) { RetainTopology = true };
                Shells(face3Ds, out result_Shell, options_Retain);
                topology = result_Shell?.Topology;
            }

            using (result_Shell)
            {
                for (int i = 0; i < point3Ds.Count; i++)
                {
                    bool? inside = topology != null ? Query.IsPointInside(topology, point3Ds[i], tolerance) : null;
                    if (inside == null)
                    {
                        inside = shell.InRange(point3Ds[i], tolerance) || shell.Inside(point3Ds[i], tolerance: tolerance);
                    }

                    if (inside == true)
                    {
                        indices.Add(i);
                    }
                }
            }

            return indices;
        }
    }
}
