// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (c) 2020-2026 Michal Dengusiak & Jakub Ziolkowski and contributors

using SAM.Core;
using SAM.Core.OCCT;
using SAM.Geometry.Planar;
using SAM.Geometry.Spatial;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SAM.Geometry.OCCT
{
    public static partial class Create
    {
        /// <summary>
        /// Creates closed Shells from vertical wall Face3Ds only (issue #24): the
        /// floors and roofs are generated by the OCCT engine. Wall bottom/top
        /// elevations are clustered within <paramref name="snapTolerance"/> (so walls
        /// that do not meet at exactly the same level still share one floor level),
        /// a padded horizontal rectangular patch is added per elevation, and a single
        /// BOPAlgo_MakerVolume pass over walls + patches produces the cells. Regions
        /// not enclosed laterally by walls stay unbounded and are dropped by OCCT;
        /// plan-enclosed voids (courtyards) become shells, matching the managed SAM
        /// CreateShells behaviour. Walls of different heights produce stacked cells
        /// per level - merge them downstream with MergeSmallShells/ShellsUnion.
        /// <paramref name="horizontalFace3Ds"/> returns the newly created horizontal
        /// floor/roof faces, deduplicated by OCCT topology key so an interior floor
        /// shared by two cells appears once. Non-planar input is not supported by the
        /// native make_face - triangulate such faces first (SAMOCCT.TriangulateSurface).
        /// Returns null on failure - inspect result diagnostics (SAM_OCCT_VERTICAL_SHELLS_*).
        /// </summary>
        public static List<Shell> ShellsFromVerticalFace3Ds(
            IEnumerable<Face3D> face3Ds,
            out List<Face3D> horizontalFace3Ds,
            out OcctCellComplexResult result,
            IEnumerable<double> elevations = null,
            double snapTolerance = Tolerance.MacroDistance,
            OcctBuildOptions options = null,
            double angleTolerance = Tolerance.Angle,
            double distanceTolerance = Tolerance.MacroDistance)
        {
            horizontalFace3Ds = null;
            result = new OcctCellComplexResult();

            List<Face3D> face3Ds_Wall = face3Ds?.Where(x => x != null).ToList();
            if (face3Ds_Wall == null || face3Ds_Wall.Count == 0)
            {
                result.AddDiagnostic(OcctDiagnosticSeverity.Error, "SAM_OCCT_VERTICAL_SHELLS_INPUT_EMPTY", "No vertical Face3D geometry was supplied.");
                return null;
            }

            // Non-vertical faces are kept - a sloped face still bounds cells and skipping
            // it would silently open volumes - but flagged, and remembered so their planes
            // are not reported as newly created horizontal faces.
            double maxNormalZ = Math.Sin(angleTolerance);
            List<Plane> planes_NonVertical = new List<Plane>();
            for (int i = 0; i < face3Ds_Wall.Count; i++)
            {
                Plane plane = face3Ds_Wall[i].GetPlane();
                if (plane == null)
                {
                    result.AddDiagnostic(OcctDiagnosticSeverity.Warning, "SAM_OCCT_VERTICAL_SHELLS_NON_VERTICAL_FACE", "Face3D plane could not be computed.", i);
                    continue;
                }

                if (Math.Abs(plane.Normal.Z) > maxNormalZ)
                {
                    planes_NonVertical.Add(plane);
                    result.AddDiagnostic(OcctDiagnosticSeverity.Warning, "SAM_OCCT_VERTICAL_SHELLS_NON_VERTICAL_FACE", string.Format("Face3D is not vertical (normal Z = {0:0.###}). It is kept as a boundary but no floor/roof level is derived from it.", plane.Normal.Z), i);
                }
            }

            List<double> elevations_Temp = elevations != null ? Query.ClusteredElevations(elevations, snapTolerance) : Query.ClusteredElevations(face3Ds_Wall, snapTolerance);
            if (elevations_Temp == null || elevations_Temp.Count < 2)
            {
                result.AddDiagnostic(OcctDiagnosticSeverity.Error, "SAM_OCCT_VERTICAL_SHELLS_INSUFFICIENT_ELEVATIONS", "At least two distinct elevations are required to cap the walls with floors and roofs.");
                return null;
            }

            result.AddDiagnostic(OcctDiagnosticSeverity.Info, "SAM_OCCT_VERTICAL_SHELLS_ELEVATIONS", string.Format("Creating horizontal patches at {0} elevation(s): {1}.", elevations_Temp.Count, string.Join(", ", elevations_Temp.Select(x => x.ToString("0.###")))));

            BoundingBox3D boundingBox3D = new BoundingBox3D(face3Ds_Wall.ConvertAll(x => x.GetBoundingBox()));
            if (boundingBox3D == null || !boundingBox3D.IsValid())
            {
                result.AddDiagnostic(OcctDiagnosticSeverity.Error, "SAM_OCCT_VERTICAL_SHELLS_INPUT_EMPTY", "Bounding box of the input Face3Ds could not be computed.");
                return null;
            }

            options = options == null ? new OcctBuildOptions() : new OcctBuildOptions(options);

            // Patch must overhang the walls so MakerVolume cuts cleanly through them.
            double margin = Math.Max(1.0, boundingBox3D.Min.Distance(boundingBox3D.Max) * 0.1);

            List<Point3D> cornerPoint3Ds = boundingBox3D.GetPoints();
            List<Face3D> allFace3Ds = new List<Face3D>(face3Ds_Wall);
            foreach (double elevation in elevations_Temp)
            {
                Plane plane = new Plane(new Point3D(0, 0, elevation), new Vector3D(0, 0, 1));

                List<Point2D> point2Ds = cornerPoint3Ds?.ConvertAll(x => plane.Convert(x)).FindAll(x => x != null);
                if (point2Ds == null || point2Ds.Count == 0)
                {
                    continue;
                }

                Face3D patchFace3D = new Face3D(plane, new Rectangle2D(new BoundingBox2D(point2Ds, margin)));
                if (patchFace3D != null)
                {
                    allFace3Ds.Add(patchFace3D);
                }
            }

            if (!Native.OcctCellComplexBuilder.TryBuild(allFace3Ds, options, result))
            {
                return null;
            }

            if (result.Cells == null || result.Cells.Count == 0)
            {
                return null;
            }

            // Horizontal cell faces are the generated floors/roofs - input walls are
            // vertical, so they are all new. Interior floors are shared by two cells
            // and deduped by the OCCT topology key. Faces lying on the plane of a
            // kept non-vertical input are excluded - those came from the user.
            horizontalFace3Ds = new List<Face3D>();
            HashSet<int> topologyKeys = new HashSet<int>();
            double minDotProduct = Math.Cos(angleTolerance);
            foreach (OcctCell cell in result.Cells)
            {
                if (cell?.Faces == null)
                {
                    continue;
                }

                foreach (OcctCellFace cellFace in cell.Faces)
                {
                    Face3D face3D = cellFace?.Face3D;
                    Plane facePlane = face3D?.GetPlane();
                    if (facePlane == null)
                    {
                        continue;
                    }

                    if (Math.Abs(facePlane.Normal.Z) < minDotProduct)
                    {
                        continue;
                    }

                    bool fromInput = false;
                    foreach (Plane plane_NonVertical in planes_NonVertical)
                    {
                        if (Math.Abs(facePlane.Normal.DotProduct(plane_NonVertical.Normal)) < minDotProduct)
                        {
                            continue;
                        }

                        if (plane_NonVertical.Distance(facePlane.Origin) > distanceTolerance)
                        {
                            continue;
                        }

                        fromInput = true;
                        break;
                    }

                    if (fromInput)
                    {
                        continue;
                    }

                    if (cellFace.TopologyKey != 0 && !topologyKeys.Add(cellFace.TopologyKey))
                    {
                        continue;
                    }

                    horizontalFace3Ds.Add(face3D);
                }
            }

            result.AddDiagnostic(OcctDiagnosticSeverity.Info, "SAM_OCCT_VERTICAL_SHELLS_BUILD_SUCCESS", string.Format("OCCT created {0} shell(s) and {1} horizontal floor/roof face(s) from {2} vertical face(s).", result.Cells.Count, horizontalFace3Ds.Count, face3Ds_Wall.Count));
            return result.Shells?.ToList();
        }
    }
}
