// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (c) 2020-2026 Michal Dengusiak & Jakub Ziolkowski and contributors

using Grasshopper.Kernel;
using Grasshopper.Kernel.Types;
using SAM.Core;
using SAM.Core.Grasshopper;
using SAM.Core.OCCT;
using SAM.Geometry.OCCT;
using SAM.Geometry.Spatial;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SAM.Geometry.Grasshopper.OCCT
{
    public class SAMOCCTCreateShellsFromVerticalFace3Ds : GH_SAMVariableOutputParameterComponent
    {
        public override Guid ComponentGuid => new Guid("b772f03a-b4ff-42e3-ab7c-4acd08162de2");

        public override string LatestComponentVersion => "0.1.3";

        protected override System.Drawing.Bitmap Icon => SAMOCCTIcon.SAM_OCCT24;

        public SAMOCCTCreateShellsFromVerticalFace3Ds()
          : base("SAMOCCT.CreateShellsFromVerticalFace3Ds", "SAMOCCT.CreateShellsFromVerticalFace3Ds", "Create closed SAM Shell volumes from vertical wall Face3Ds only - the floors and roofs are generated by OCCT at the wall bottom/top elevations. Feed the shells into SAMOCCT.MergeSmallShells or SAMOCCT.CreateAdjacencyCluster.", "SAM", "OCCT")
        {
        }

        protected override GH_SAMParam[] Inputs
        {
            get
            {
                List<GH_SAMParam> result = new List<GH_SAMParam>();

                global::Grasshopper.Kernel.Parameters.Param_GenericObject face3Ds = new global::Grasshopper.Kernel.Parameters.Param_GenericObject() { Name = "_face3Ds", NickName = "_face3Ds", Description = "Vertical wall faces enclosing the spaces in plan. Accepts SAM Face3Ds and geometry that converts to Face3Ds. Non-planar faces are not supported - triangulate them first.", Access = GH_ParamAccess.list };
                face3Ds.DataMapping = GH_DataMapping.Flatten;
                result.Add(new GH_SAMParam(face3Ds, ParamVisibility.Binding));

                global::Grasshopper.Kernel.Parameters.Param_String roofMode = new global::Grasshopper.Kernel.Parameters.Param_String() { Name = "roofMode_", NickName = "roofMode_", Description = "How to cap the walls on top: Flat (horizontal floors/roofs at every wall level, the default) or Sloped (horizontal floors, but one roof that follows the wall tops - planar when the tops are coplanar, triangulated for gable/hip/stepped tops).", Access = GH_ParamAccess.item };
                roofMode.SetPersistentData(OcctRoofMode.Flat.ToString());
                result.Add(new GH_SAMParam(roofMode, ParamVisibility.Voluntary));

                global::Grasshopper.Kernel.Parameters.Param_GenericObject points = new global::Grasshopper.Kernel.Parameters.Param_GenericObject() { Name = "points_", NickName = "points_", Description = "Optional selection points - one per room. When supplied, only shells that contain a point are kept (point-in-solid classified by OCCT), discarding courtyards and other plan-enclosed voids.", Access = GH_ParamAccess.list, Optional = true };
                points.DataMapping = GH_DataMapping.Flatten;
                result.Add(new GH_SAMParam(points, ParamVisibility.Voluntary));

                global::Grasshopper.Kernel.Parameters.Param_Number elevations = new global::Grasshopper.Kernel.Parameters.Param_Number() { Name = "elevations_", NickName = "elevations_", Description = "Optional floor/roof elevations. When supplied they override the auto-detected levels (in Sloped mode they set the floor levels; the roof still follows the wall tops).", Access = GH_ParamAccess.list, Optional = true };
                elevations.DataMapping = GH_DataMapping.Flatten;
                result.Add(new GH_SAMParam(elevations, ParamVisibility.Voluntary));

                global::Grasshopper.Kernel.Parameters.Param_Number snapTolerance = new global::Grasshopper.Kernel.Parameters.Param_Number() { Name = "snapTolerance_", NickName = "snapTolerance_", Description = "Wall bottom/top elevations closer than this are merged into one floor/roof level.", Access = GH_ParamAccess.item };
                snapTolerance.SetPersistentData(Tolerance.MacroDistance);
                result.Add(new GH_SAMParam(snapTolerance, ParamVisibility.Voluntary));

                global::Grasshopper.Kernel.Parameters.Param_Number tolerance = new global::Grasshopper.Kernel.Parameters.Param_Number() { Name = "tolerance_", NickName = "tolerance_", Description = "OCCT build tolerance [m]", Access = GH_ParamAccess.item };
                tolerance.SetPersistentData(Tolerance.Distance);
                result.Add(new GH_SAMParam(tolerance, ParamVisibility.Voluntary));

                global::Grasshopper.Kernel.Parameters.Param_Number fuzzyTolerance = new global::Grasshopper.Kernel.Parameters.Param_Number() { Name = "fuzzyTolerance_", NickName = "fuzzyTolerance_", Description = "OCCT fuzzy tolerance [m]", Access = GH_ParamAccess.item };
                fuzzyTolerance.SetPersistentData(Tolerance.MacroDistance);
                result.Add(new GH_SAMParam(fuzzyTolerance, ParamVisibility.Voluntary));

                global::Grasshopper.Kernel.Parameters.Param_Number weldTolerance = new global::Grasshopper.Kernel.Parameters.Param_Number() { Name = "weldTolerance_", NickName = "weldTolerance_", Description = "Cleanup for drifted input (model units). When greater than 0, input face corners closer together than this distance are snapped to one shared point BEFORE building, so faces that do not quite meet seal into a watertight shell. Use it when the model fails to close, or bakes with hairline gaps / a 'missing' face, because adjacent faces do not share identical vertices (common with imported or auto-generated geometry). Set it just above the largest gap between faces that should touch (typically 0.05-0.1) - too large collapses real detail. 0 (default) disables welding and leaves the input untouched.", Access = GH_ParamAccess.item };
                weldTolerance.SetPersistentData(0.0);
                result.Add(new GH_SAMParam(weldTolerance, ParamVisibility.Voluntary));

                global::Grasshopper.Kernel.Parameters.Param_Boolean run = new global::Grasshopper.Kernel.Parameters.Param_Boolean() { Name = "_run", NickName = "_run", Description = "Run", Access = GH_ParamAccess.item };
                run.SetPersistentData(false);
                result.Add(new GH_SAMParam(run, ParamVisibility.Binding));

                return result.ToArray();
            }
        }

        protected override GH_SAMParam[] Outputs
        {
            get
            {
                List<GH_SAMParam> result = new List<GH_SAMParam>();
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_GenericObject() { Name = "Shells", NickName = "Shells", Description = "Closed SAM Shell volumes created by OCCT from the walls and generated floors/roofs.", Access = GH_ParamAccess.list }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_GenericObject() { Name = "Face3Ds", NickName = "Face3Ds", Description = "Newly created horizontal Face3Ds (floors and roofs), deduplicated so an interior floor shared by two shells appears once.", Access = GH_ParamAccess.list }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_String() { Name = "Diagnostics", NickName = "Diagnostics", Description = "OCCT diagnostics", Access = GH_ParamAccess.list }, ParamVisibility.Binding));
                result.Add(new GH_SAMParam(new global::Grasshopper.Kernel.Parameters.Param_Boolean() { Name = "Successful", NickName = "Successful", Description = "Run successfully?", Access = GH_ParamAccess.item }, ParamVisibility.Binding));
                return result.ToArray();
            }
        }

        protected override void SolveInstance(IGH_DataAccess dataAccess)
        {
            int index_Successful = Params.IndexOfOutputParam("Successful");
            if (index_Successful != -1)
            {
                dataAccess.SetData(index_Successful, false);
            }

            int index;

            bool run = false;
            index = Params.IndexOfInputParam("_run");
            if (index == -1 || !dataAccess.GetData(index, ref run) || !run)
            {
                return;
            }

            List<GH_ObjectWrapper> objectWrappers = new List<GH_ObjectWrapper>();
            index = Params.IndexOfInputParam("_face3Ds");
            if (index == -1 || !dataAccess.GetDataList(index, objectWrappers) || objectWrappers == null)
            {
                AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Invalid data");
                return;
            }

            OcctRoofMode roofMode = OcctRoofMode.Flat;
            string roofModeText = null;
            index = Params.IndexOfInputParam("roofMode_");
            if (index != -1 && dataAccess.GetData(index, ref roofModeText) && !string.IsNullOrWhiteSpace(roofModeText))
            {
                if (!Enum.TryParse(roofModeText.Trim(), true, out roofMode))
                {
                    AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, string.Format("Unrecognised roofMode_ '{0}'. Using {1}.", roofModeText, OcctRoofMode.Flat));
                    roofMode = OcctRoofMode.Flat;
                }
            }

            List<double> elevations = new List<double>();
            index = Params.IndexOfInputParam("elevations_");
            if (index != -1)
            {
                dataAccess.GetDataList(index, elevations);
            }

            double snapTolerance = Tolerance.MacroDistance;
            index = Params.IndexOfInputParam("snapTolerance_");
            if (index != -1)
            {
                dataAccess.GetData(index, ref snapTolerance);
            }

            double tolerance = Tolerance.Distance;
            index = Params.IndexOfInputParam("tolerance_");
            if (index != -1)
            {
                dataAccess.GetData(index, ref tolerance);
            }

            double fuzzyTolerance = Tolerance.MacroDistance;
            index = Params.IndexOfInputParam("fuzzyTolerance_");
            if (index != -1)
            {
                dataAccess.GetData(index, ref fuzzyTolerance);
            }

            double weldTolerance = 0;
            index = Params.IndexOfInputParam("weldTolerance_");
            if (index != -1)
            {
                dataAccess.GetData(index, ref weldTolerance);
            }

            List<GH_ObjectWrapper> pointWrappers = new List<GH_ObjectWrapper>();
            index = Params.IndexOfInputParam("points_");
            if (index != -1)
            {
                dataAccess.GetDataList(index, pointWrappers);
            }

            List<Face3D> face3Ds = new List<Face3D>();
            foreach (GH_ObjectWrapper objectWrapper in objectWrappers)
            {
                if (Query.TryGetSAMGeometries(objectWrapper, out List<Face3D> face3Ds_Temp) && face3Ds_Temp != null)
                {
                    face3Ds.AddRange(face3Ds_Temp);
                }
            }

            List<Point3D> point3Ds = new List<Point3D>();
            foreach (GH_ObjectWrapper pointWrapper in pointWrappers)
            {
                if (Query.TryGetSAMGeometries(pointWrapper, out List<Point3D> point3Ds_Temp) && point3Ds_Temp != null)
                {
                    point3Ds.AddRange(point3Ds_Temp);
                }
            }

            List<Shell> shells = Geometry.OCCT.Create.ShellsFromVerticalFace3Ds(
                face3Ds,
                out List<Face3D> horizontalFace3Ds,
                out OcctCellComplexResult result,
                elevations == null || elevations.Count == 0 ? null : elevations,
                snapTolerance,
                new OcctBuildOptions { Tolerance = tolerance, FuzzyTolerance = fuzzyTolerance },
                Tolerance.Angle,
                Tolerance.MacroDistance,
                roofMode,
                point3Ds.Count == 0 ? null : point3Ds,
                weldTolerance);

            List<string> diagnostics = result?.Diagnostics?.Select(x => x.ToString()).ToList();

            index = Params.IndexOfOutputParam("Shells");
            if (index != -1)
            {
                dataAccess.SetDataList(index, shells);
            }

            index = Params.IndexOfOutputParam("Face3Ds");
            if (index != -1)
            {
                dataAccess.SetDataList(index, horizontalFace3Ds);
            }

            index = Params.IndexOfOutputParam("Diagnostics");
            if (index != -1)
            {
                dataAccess.SetDataList(index, diagnostics);
            }

            if (index_Successful != -1)
            {
                dataAccess.SetData(index_Successful, result != null && result.Success && shells != null && shells.Count > 0);
            }

            if (diagnostics != null)
            {
                foreach (string diagnostic in diagnostics)
                {
                    AddRuntimeMessage(GH_RuntimeMessageLevel.Remark, diagnostic);
                }
            }
        }
    }
}
