// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (c) 2020-2026 Michal Dengusiak & Jakub Ziolkowski and contributors

using System.Drawing;
using System.IO;
using System.Reflection;

namespace SAM.Geometry.Grasshopper.OCCT
{
    internal static class SAMOCCTIcon
    {
        internal static Bitmap SAM_OCCT24
        {
            get
            {
                Assembly assembly = typeof(SAMOCCTIcon).Assembly;
                using (Stream stream = assembly.GetManifestResourceStream("SAM.Geometry.Grasshopper.OCCT.Resources.SAM_OCCT24.png"))
                {
                    if (stream == null)
                    {
                        return null;
                    }

                    using (Bitmap bitmap = new Bitmap(stream))
                    {
                        return new Bitmap(bitmap);
                    }
                }
            }
        }


        // <sam-gh-icons> generated by design/grasshopper-icons/tools/integrate.py (SAM GH icon redesign)
        private static Bitmap LoadIcon(string name)
        {
            using (Stream stream = typeof(SAMOCCTIcon).Assembly.GetManifestResourceStream("SAM.Geometry.Grasshopper.OCCT.Resources.Icons." + name + ".png"))
            {
                if (stream == null)
                {
                    return null;
                }

                using (Bitmap bitmap = new Bitmap(stream))
                {
                    return new Bitmap(bitmap);
                }
            }
        }

        internal static Bitmap SAM_GH_FacePluralMerge => LoadIcon("SAM_GH_FacePluralMerge");
        internal static Bitmap SAM_GH_FaceSplit => LoadIcon("SAM_GH_FaceSplit");
        internal static Bitmap SAM_GH_FaceTriangulate => LoadIcon("SAM_GH_FaceTriangulate");
        internal static Bitmap SAM_GH_FaceValidate => LoadIcon("SAM_GH_FaceValidate");
        internal static Bitmap SAM_GH_SectionBoxSection => LoadIcon("SAM_GH_SectionBoxSection");
        internal static Bitmap SAM_GH_ShellCalculate => LoadIcon("SAM_GH_ShellCalculate");
        internal static Bitmap SAM_GH_ShellDifference => LoadIcon("SAM_GH_ShellDifference");
        internal static Bitmap SAM_GH_ShellIntersect => LoadIcon("SAM_GH_ShellIntersect");
        internal static Bitmap SAM_GH_ShellMerge => LoadIcon("SAM_GH_ShellMerge");
        internal static Bitmap SAM_GH_ShellModify => LoadIcon("SAM_GH_ShellModify");
        internal static Bitmap SAM_GH_ShellOffset => LoadIcon("SAM_GH_ShellOffset");
        internal static Bitmap SAM_GH_ShellPluralCreate => LoadIcon("SAM_GH_ShellPluralCreate");
        internal static Bitmap SAM_GH_ShellPluralExport => LoadIcon("SAM_GH_ShellPluralExport");
        internal static Bitmap SAM_GH_ShellPluralImport => LoadIcon("SAM_GH_ShellPluralImport");
        internal static Bitmap SAM_GH_ShellPluralMerge => LoadIcon("SAM_GH_ShellPluralMerge");
        internal static Bitmap SAM_GH_ShellPluralUnion => LoadIcon("SAM_GH_ShellPluralUnion");
        internal static Bitmap SAM_GH_ShellSplit => LoadIcon("SAM_GH_ShellSplit");
        internal static Bitmap SAM_GH_ShellUpdate => LoadIcon("SAM_GH_ShellUpdate");
        // </sam-gh-icons>
    }
}
