// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (c) 2020-2026 Michal Dengusiak & Jakub Ziolkowski and contributors

using System.Drawing;
using System.IO;
using System.Reflection;

namespace SAM.Analytical.Grasshopper.OCCT
{
    internal static class SAMOCCTIcon
    {
        internal static Bitmap SAM_OCCT24
        {
            get
            {
                Assembly assembly = typeof(SAMOCCTIcon).Assembly;
                using (Stream stream = assembly.GetManifestResourceStream("SAM.Analytical.Grasshopper.OCCT.Resources.SAM_OCCT24.png"))
                {
                    if (stream == null)
                    {
                        return null;
                    }

                    using (Bitmap bitmap = new Bitmap(stream))
                    {
                        return new Bitmap(bitmap);
                    }
                }
            }
        }


        // <sam-gh-icons> generated by design/grasshopper-icons/tools/integrate.py (SAM GH icon redesign)
        private static Bitmap LoadIcon(string name)
        {
            using (Stream stream = typeof(SAMOCCTIcon).Assembly.GetManifestResourceStream("SAM.Analytical.Grasshopper.OCCT.Resources.Icons." + name + ".png"))
            {
                if (stream == null)
                {
                    return null;
                }

                using (Bitmap bitmap = new Bitmap(stream))
                {
                    return new Bitmap(bitmap);
                }
            }
        }

        internal static Bitmap SAM_GH_AlgorithmGet => LoadIcon("SAM_GH_AlgorithmGet");
        internal static Bitmap SAM_GH_AlgorithmRun => LoadIcon("SAM_GH_AlgorithmRun");
        internal static Bitmap SAM_GH_CellComplex => LoadIcon("SAM_GH_CellComplex");
        internal static Bitmap SAM_GH_ClusterCreate => LoadIcon("SAM_GH_ClusterCreate");
        internal static Bitmap SAM_GH_ClusterMerge => LoadIcon("SAM_GH_ClusterMerge");
        internal static Bitmap SAM_GH_ClusterRun => LoadIcon("SAM_GH_ClusterRun");
        internal static Bitmap SAM_GH_PanelPluralCreate => LoadIcon("SAM_GH_PanelPluralCreate");
        internal static Bitmap SAM_GH_PanelPluralExtend => LoadIcon("SAM_GH_PanelPluralExtend");
        internal static Bitmap SAM_GH_PanelPluralMerge => LoadIcon("SAM_GH_PanelPluralMerge");
        internal static Bitmap SAM_GH_PanelPluralModify => LoadIcon("SAM_GH_PanelPluralModify");
        internal static Bitmap SAM_GH_SpacePluralMerge => LoadIcon("SAM_GH_SpacePluralMerge");
        internal static Bitmap SAM_GH_SpacePluralValidate => LoadIcon("SAM_GH_SpacePluralValidate");
        // </sam-gh-icons>
    }
}
